myapp/urls.py
from django.conf.urls import url, include
from . import views
from django.views.generic import RedirectView

app_name = "myapp"

urlpatterns = [
    url(r'^$',views.myapphome, name='home'),
    url(r'myapp',RedirectView.as_view(pattern_name='myapp:home', permanent=True)),
    url(r'login',views.signin, name='login'),
    url(r'register',views.signup, name='signup'),
    url(r'logout',views.signout, name='logout')
   
]

myhome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from myhome import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'',views.home)
    url(r'',include('myapp.urls'))
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	genre = models.CharField(max_length=30, null=True)
	birth_date = models.DateField(null=True)
	merritual_staus = models.CharField(max_length=30, null=True)

@receiver(post_save, sender=User)
def update_user_profile(sender,instance,created, **kwargs):
	if created:
		Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender,instance,**kwargs):
	instance.profile.save()

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
	GENRE_CHOICES =(
		('m','male'),
		('f','female')
		)
	MERRITUAL_CHOICES =(
		('mr','merried'),
		('bc', 'bechelor')
		)
	genre=forms.ChoiceField(choices=GENRE_CHOICES)
	first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
	last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
	email = forms.CharField(max_length=40, required=False, help_text='required.valid enmail id')
	birth_date = forms.DateField(help_text='YYYY/MM/DD')
	merritual_staus = forms.ChoiceField(choices=MERRITUAL_CHOICES)


	class Meta:
		model = User
		fields = ('username', 'genre','first_name', 'last_name','email','birth_date','merritual_staus','password1','password2')

myapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm  
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from myapp.forms import SignUpForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def myapphome(request):
	return render(request,'myapp/myapphome.html')


def signin(request):
	if request.user.is_authenticated:
		messages.success(request,'already logged in')
		return render(request,'myapp/myapphome.html')
	if request.method == 'POST':
		# import pdb;pdb.set_trace()
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			messages.success(request,'You are successfully logged in')
			return redirect('myapp:home')
		else:
			messages.error(request,'User Id not matched')
			form = AuthenticationForm(request.POST)
			return render(request,'myapp/login.html',{'form':form})
	else:
		form = AuthenticationForm()
		return render(request,'myapp/login.html',{'form':form})


def signup(request):
	if request.method =='POST':
		
		form = SignUpForm(request.POST)
		if form.is_valid():
			user = form.save()
			user.refresh_from_db()
			user.profile.genre = form.cleaned_data.get('genre')
			user.profile.birth_date = form.cleaned_data.get('birth_date')
			user.profile.merritual_staus = form.cleaned_data.get('merritual_staus')
			user.save()
			messages.success(request,"Successfully registered with us, plz signin now")
			return redirect('myapp:login')
	else:
		form = SignUpForm()
	return render(request,'myapp/signup.html',{'form':form})




def signout(request):
	logout(request)
	return redirect('myapp:login')

myhome/views.py
from django.shortcuts import render



def home(request):
	return render(request,'home.html')

myapp/templates/myapp/login.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block contents %}
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form method="POST">
					{% csrf_token %}
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" name="username" class="form-control" placeholder="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" name="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="{% url 'myapp:signup' %}">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
	

{% endblock %}

myapp/templates/myapp/myapphome.html
{% extends 'base.html' %}
{% block contents %}
{% if user %}
<h1>Hello {{user.username }}</h1>

<h1>Welcome to myapp home page </h1><br>

<h2>You can now logout </h2>

<a href="{% url 'myapp:logout' %}"><button type="button" class="btn btn-warning">Logout</button></a>
{% else %}
<h1>You are not logged in kindly login </h1>
{% endif %}
{% endblock %}

myapp/templates/myapp/signup.html
{% extends 'base.html' %}

{% block contents %}
<!-- This snippet uses Font Awesome 5 Free as a dependency. You can download it at fontawesome.io! -->

<body>
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-xl-9 mx-auto">
        <div class="card card-signin flex-row my-5">
          <div class="card-img-left d-none d-md-flex">
             <!-- Background image for card set in CSS! -->
          </div>
          <div class="card-body">
            <h5 class="card-title text-center">Register</h5>
            <form class="form-signin" method="POST">
            	{% csrf_token %}
              <div class="form-label-group">
                <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
                <label for="username">Username</label>
              </div>

               <div class="form-label-group">
               	<select name="genre" class="form-control">
				        <option value="m">Male</option>
				        <option value="f">Female</option>
				        </select>                
              </div>          
              <div class="form-label-group">
                <input type="text" name="first_name" id="first_name" class="form-control" placeholder="First Name" required>
                <label for="first_name">First Name</label>
              </div>
               <div class="form-label-group">
                <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Last Name" required>
                <label for="last_name">Last Name</label>
              </div>

              <div class="form-label-group">
                <input type="email" name="email" id="email" class="form-control" placeholder="Email address" required>
                <label for="email">Email address</label>
              </div>
              <div class="form-label-group">
                <input type="text" name="birth_date" id="birth_date" class="form-control" placeholder="Birth Date YY/mm/dd" required>
                <label for="birth_date">birth_date</label>
              </div>
              <div class="form-label-group">
                  <select name="merritual_staus" id="merritual_staus" class="form-control">
                  <option value="mr">Married</option>
                  <option value="bc">Bachelor</option>
                  
                </select>
              </div>
              
              <hr>

              <div class="form-label-group">
                <input type="password" id="password1" name="password1" class="form-control" placeholder="Password" required>
                <label for="password1">Password</label>
              </div>
              
              <div class="form-label-group">
                <input type="password" id="password2" name="password2" class="form-control" placeholder="Password" required>
                <label for="password2">Confirm password</label>
              </div>

              <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Register</button>
              <a class="d-block text-center mt-2 small" href="{% url 'myapp:login' %}">Sign In</a>
              <hr class="my-4">
              <button class="btn btn-lg btn-google btn-block text-uppercase" type="submit"><i class="fab fa-google mr-2"></i> Sign up with Google</button>
              <button class="btn btn-lg btn-facebook btn-block text-uppercase" type="submit"><i class="fab fa-facebook-f mr-2"></i> Sign up with Facebook</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

<style type="text/css">
	:root {
  --input-padding-x: 1.5rem;
  --input-padding-y: .75rem;
  --select-padding-x: 1.5rem;
  --select-padding-y: .75rem;
}

body {
  background: #007bff;
  background: linear-gradient(to right, #0062E6, #33AEFF);
}

.card-signin {
  border: 0;
  border-radius: 1rem;
  box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.card-signin .card-title {
  margin-bottom: 2rem;
  font-weight: 300;
  font-size: 1.5rem;
}

.card-signin .card-img-left {
  width: 45%;
  /* Link to your background image using in the property below! */
  background: scroll center url('https://source.unsplash.com/WEQbe2jBg40/414x512');
  background-size: cover;
}

.card-signin .card-body {
  padding: 2rem;
}

.form-signin {
  width: 100%;
}

.form-signin .btn {
  font-size: 80%;
  border-radius: 5rem;
  letter-spacing: .1rem;
  font-weight: bold;
  padding: 1rem;
  transition: all 0.2s;
}

.form-label-group {
  position: relative;
  margin-bottom: 1rem;
}

.form-label-group input {
  height: auto;
  border-radius: 2rem;
}

.form-label-group>input,
.form-label-group>label {
  padding: var(--input-padding-y) var(--input-padding-x);
}

.form-label-group>label {
  position: absolute;
  top: 0;
  left: 0;
  display: block;
  width: 100%;
  margin-bottom: 0;
  /* Override default `<label>` margin */
  line-height: 1.5;
  color: #495057;
  border: 1px solid transparent;
  border-radius: .25rem;
  transition: all .1s ease-in-out;
}

.form-label-group input::-webkit-input-placeholder {
  color: transparent;
}

.form-label-group input:-ms-input-placeholder {
  color: transparent;
}

.form-label-group input::-ms-input-placeholder {
  color: transparent;
}

.form-label-group input::-moz-placeholder {
  color: transparent;
}

.form-label-group input::placeholder {
  color: transparent;
}

.form-label-group input:not(:placeholder-shown) {
  padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
  padding-bottom: calc(var(--input-padding-y) / 3);
}

.form-label-group input:not(:placeholder-shown)~label {
  padding-top: calc(var(--input-padding-y) / 3);
  padding-bottom: calc(var(--input-padding-y) / 3);
  font-size: 12px;
  color: #777;
}

.btn-google {
  color: white;
  background-color: #ea4335;
}

.btn-facebook {
  color: white;
  background-color: #3b5998;
}

</style>
{% endblock %}

myhome/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
  </head>
  <body>
    <div class="container">
    {% block main %}
    {% include 'messages.html' %}
        

    {% block contents %}

    {% endblock %}
    {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  </body>
</html>

myhome/templates/home.html
{% extends 'base.html' %}

{% block contents %}
	<h1>Homepage</h1>
{% endblock %}

myhome/templates/messages.html
{% if messages %}
  {% for msg in messages %}
    <div class="alert alert-info alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      {{msg.message}}
    </div>
  {% endfor %}
{% endif %}